### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by MichelML** [cheminfo-js/sdf-parser#2]
Hi,

I had a look at the code and parts of it seem to be browser friendly. Could you update the doc on how to use the package for browser based situations?

If not browser friendly, can you describe the difficulties you had implementing this? I might give you a hand on this one.

**Comment by lpatiny** [comment]
The browser version is available on our CDN:

https://www.lactame.com/

In particular you should load

https://www.lactame.com/lib/sdf-parser/3.1.0/sdf-parser.js

that will add in window: SDFParser that you may use like:

`var parsed = SDFParser(mySdfFile);`
